services:
  db:
    image: mysql:8.0
    container_name: biblio-db
    restart: always
    environment:
      MYSQL_DATABASE: biblioonline
      MYSQL_ROOT_PASSWORD: password
    networks:
      - biblio-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  utility:
    image: usuario_ejemplo/biblio-utility:latest
    container_name: biblio-utility
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=tu_correo@gmail.com
      - SPRING_MAIL_PASSWORD=tu_password_aplicacion
    networks:
      - biblio-net
    ports:
      - "8081:8080"

  app:
    image: usuario_ejemplo/biblio-app:latest
    container_name: biblio-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/biblioonline
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - UTILITY_SERVICE_URL=http://utility:8080
    networks:
      - biblio-net
    ports:
      - "8443:8443"

networks:
  biblio-net:
    driver: bridge